Vagrant.configure("2") do |config|
  # Global VMware Provider Settings
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.linked_clone = true 
  end

  # --- NODE 1: Analysis Server ---
  config.vm.define "analyst_srv" do |s|
    s.vm.box = "bento/ubuntu-22.04"
    s.vm.hostname = "analyst-srv"
    s.vm.network "private_network", ip: "192.168.114.10"

    # Updated to your generic script name
    s.vm.provision "shell", path: "scripts/setup_tools.sh"
  end

  # --- NODE 2: Research Endpoint ---
  config.vm.define "endpoint_win" do |v|
    v.vm.box = "gusztavvargadr/windows-10-21h2-enterprise"
    v.vm.hostname = "endpoint-win"
    v.vm.network "private_network", ip: "192.168.114.20"
    v.vm.provider "vmware_desktop" do |vmw|
      vmw.memory = 4096
      vmw.cpus = 2
    end

    # Updated to your generic script name
    v.vm.provision "shell", path: "scripts/prepare_endpoint.ps1"
  end
end
